language: python
python:
  - "3.2"

before_install:
   #found this in https://github.com/keflavich/despotic/blob/master/.travis.yml
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq tk8.5"
  - "sudo apt-get install -qq python3-tk"

install:
  - "./.travis_scripts/install.sh"

script:
  - "./.travis_scripts/test.sh"
